# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='fotos')),
                ('telefone', models.CharField(max_length=32)),
                ('cpf', models.CharField(max_length=32)),
                ('enderço', models.CharField(max_length=128)),
                ('contato_emergencia', models.CharField(max_length=128)),
                ('mestre', models.CharField(max_length=32)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalLancamento',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('last_modified', models.DateTimeField(blank=True, editable=False)),
                ('approved_timestamp', models.DateTimeField(blank=True, null=True)),
                ('moderation_comments', models.TextField(blank=True, null=True)),
                ('moderation_status', models.CharField(choices=[('A', 'Approved'), ('R', 'Rejected'), ('P', 'Pending')], default='P', help_text='O status "Rejected" não permite que o registro seja mostr    ado.', max_length=1, verbose_name='Status de Moderação')),
                ('autor', models.CharField(choices=[('s', 'System'), ('a', 'Admin'), ('u', 'User')], max_length=1)),
                ('credito_debito', models.CharField(choices=[('d', 'Débito'), ('c', 'Crédito')], max_length=1)),
                ('timestamp_comprovante', models.DateTimeField(verbose_name='Data do Comprovante')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('comprovante', models.TextField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical lancamento',
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalPlano',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('last_modified', models.DateTimeField(blank=True, editable=False)),
                ('approved_timestamp', models.DateTimeField(blank=True, null=True)),
                ('moderation_comments', models.TextField(blank=True, null=True)),
                ('moderation_status', models.CharField(choices=[('A', 'Approved'), ('R', 'Rejected'), ('P', 'Pending')], default='P', help_text='O status "Rejected" não permite que o registro seja mostr    ado.', max_length=1, verbose_name='Status de Moderação')),
                ('plano', models.CharField(choices=[('an', 'Anuidade'), ('ml', 'Mensalidades'), ('sh', 'Starving Hacker')], max_length=2)),
                ('validade_data_inicio', models.DateField()),
                ('data_validade_fim', models.DateField()),
                ('descricao', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical plano',
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('approved_timestamp', models.DateTimeField(blank=True, null=True)),
                ('moderation_comments', models.TextField(blank=True, null=True)),
                ('moderation_status', models.CharField(choices=[('A', 'Approved'), ('R', 'Rejected'), ('P', 'Pending')], default='P', help_text='O status "Rejected" não permite que o registro seja mostr    ado.', max_length=1, verbose_name='Status de Moderação')),
                ('autor', models.CharField(choices=[('s', 'System'), ('a', 'Admin'), ('u', 'User')], max_length=1)),
                ('credito_debito', models.CharField(choices=[('d', 'Débito'), ('c', 'Crédito')], max_length=1)),
                ('timestamp_comprovante', models.DateTimeField(verbose_name='Data do Comprovante')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('descricao', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('approved_timestamp', models.DateTimeField(blank=True, null=True)),
                ('moderation_comments', models.TextField(blank=True, null=True)),
                ('moderation_status', models.CharField(choices=[('A', 'Approved'), ('R', 'Rejected'), ('P', 'Pending')], default='P', help_text='O status "Rejected" não permite que o registro seja mostr    ado.', max_length=1, verbose_name='Status de Moderação')),
                ('plano', models.CharField(choices=[('an', 'Anuidade'), ('ml', 'Mensalidades'), ('sh', 'Starving Hacker')], max_length=2)),
                ('validade_data_inicio', models.DateField()),
                ('data_validade_fim', models.DateField()),
                ('descricao', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
