# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-10 00:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplano',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plano',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=130, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicallancamento',
            name='moderation_status',
            field=models.CharField(choices=[('A', 'Approved'), ('R', 'Rejected'), ('P', 'Pending')], default='P', help_text='O status "Rejected" não permite que o registro seja mostrado.', max_length=1, verbose_name='Status de Moderação'),
        ),
        migrations.AlterField(
            model_name='historicalplano',
            name='data_validade_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalplano',
            name='moderation_status',
            field=models.CharField(choices=[('A', 'Approved'), ('R', 'Rejected'), ('P', 'Pending')], default='P', help_text='O status "Rejected" não permite que o registro seja mostrado.', max_length=1, verbose_name='Status de Moderação'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='moderation_status',
            field=models.CharField(choices=[('A', 'Approved'), ('R', 'Rejected'), ('P', 'Pending')], default='P', help_text='O status "Rejected" não permite que o registro seja mostrado.', max_length=1, verbose_name='Status de Moderação'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plano',
            name='data_validade_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plano',
            name='moderation_status',
            field=models.CharField(choices=[('A', 'Approved'), ('R', 'Rejected'), ('P', 'Pending')], default='P', help_text='O status "Rejected" não permite que o registro seja mostrado.', max_length=1, verbose_name='Status de Moderação'),
        ),
    ]
