# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-15 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0002_auto_20170810_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplano',
            name='validade_data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plano',
            name='validade_data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
